### ISSUE TITLE
it says 2.0 but it contains 1.0

### ISSUE THREAD

**Issue by azachar** [mailin-api/sendinblue-nodejs-api-npm#1]
Hi there!

Could you please provide the correct content of the `sendinblue-api.js`?

Also it would be great to provide some real world examples and do not use relative paths in `require` definition. 

Also I am missing the version tag of this repo so it can be referenced in the npm dependency.

Thanks!

**Comment by ekta-slit** [comment]
Hello,

Thank you for contacting us.
The library was under development.
Please refer the latest library with examples on [NPM](https://www.npmjs.com/package/sendinblue-api)

Regards,
SendinBlue Team

**Comment by azachar** [comment]
Thanks!
