### ISSUE TITLE
Can't register a new subscriber : "Origin 'null' is therefore not allowed access."

### ISSUE THREAD

**Issue by palmthree-studio** [mailin-api/sendinblue-nodejs-api-npm#10]
Hello,

I use NodeJS and I want to add new subscriber with API.

But when I call the route, I have this error : 

> Failed to load https://myApp.herokuapp.com/addSubscriber: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://myWebsite.com' is therefore not allowed access. The response had HTTP status code 503.

So this is my code : 

ANGULARJS : 

[$scope.addSubscriber = function(mail,surname){

        $scope.subscriberSurname = surname;
        $scope.subscriberMail = mail;

        console.log($scope.subscriberSurname,$scope.subscriberMail);

        $.post(SERVER_SIDE_MAIL, {

                  mail: $scope.subscriberMail,

                  surname: $scope.subscriberSurname,

                  list_id: 5

              }, function(res) {}
     })
}](url)

And NODEJS Route : 

[](app.post('/addSubscriber', function(req, res, next){

  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
  
  var client = new Mailin("https://api.sendinblue.com/v2.0","MyAPIKey");
  console.log(req.body);
  var mail = req.body.mail;
  var surname = req.body.surname;
  var list_id = req.body.listid;

  data = { "email" : mail,
    "attributes" : {"PRENOM":surname},
    "listid" : listid
    }
 
  client.create_update_user(data).on('complete', function(data) {
    console.log(data);
  });

});)

I have miss something ? Please, help me ...

Thank you.

**Comment by ekta-slit** [comment]
Hi @Yngdev31 

The error you are facing is due to CORS & it is not enabled for APIs because if you do an API call from JS ( client-side ) side, for example an AJAX call, it is a big security issue. It would indeed mean that your account's API key would become public.

In order for this code to work make sure your code gets executed on server side.

Hope that helps!

Regards
SendinBlue Team

**Comment by palmthree-studio** [comment]
Hello, my NodeJS code is in external server (I use heroku).
For example, Stripe work perfectly in my server side.

An another idea ?

**Comment by ekta-slit** [comment]
Hi @Yngdev31 

It seems that CORS is not enabled for accessed URL `https://myapp.herokuapp.com/addSubscriber` from `https://myWebsite.com`.
That is why you received below error:
>Failed to load https://myApp.herokuapp.com/addSubscriber: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://myWebsite.com' is therefore not allowed access. The response had HTTP status code 503.

Thanks
