### ISSUE TITLE
[NOT SOLVED] Can't register a new subscriber : "Origin 'null' is therefore not allowed access."

### ISSUE THREAD

**Issue by palmthree-studio** [mailin-api/sendinblue-nodejs-api-npm#11]
Hello,

I use NodeJS and I want to add new subscriber with API.

But when I call the route, I have this error : 

> Failed to load https://myApp.herokuapp.com/addSubscriber: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://myWebsite.com' is therefore not allowed access. The response had HTTP status code 503.

So this is my code : 

ANGULARJS : 

[$scope.addSubscriber = function(mail,surname){

        $scope.subscriberSurname = surname;
        $scope.subscriberMail = mail;

        console.log($scope.subscriberSurname,$scope.subscriberMail);

        $.post(SERVER_SIDE_MAIL, {

                  mail: $scope.subscriberMail,

                  surname: $scope.subscriberSurname,

                  list_id: 5

              }, function(res) {}
     })
}](url)

And NODEJS Route : 

[](app.post('/addSubscriber', function(req, res, next){

  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
  
  var client = new Mailin("https://api.sendinblue.com/v2.0","MyAPIKey");
  console.log(req.body);
  var mail = req.body.mail;
  var surname = req.body.surname;
  var list_id = req.body.listid;

  data = { "email" : mail,
    "attributes" : {"PRENOM":surname},
    "listid" : listid
    }
 
  client.create_update_user(data).on('complete', function(data) {
    console.log(data);
  });

});)

Is something wrong ? Please, help me ...

Thank you.

PS : NodeJS code is in server side, I specify this because my previous post was closed even before the problem was solved.
Please do not close this one until the problem is solved. Thank you.

**Comment by ekta-slit** [comment]
Hi @Yngdev31

It seems that CORS is not enabled for accessed URL https://myapp.herokuapp.com/addSubscriber from https://myWebsite.com.
That is why you received below error:

>Failed to load https://myApp.herokuapp.com/addSubscriber: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://myWebsite.com' is therefore not allowed access. The response had HTTP status code 503.

Hope that helps!

Thanks
SendinBlue Team
