### ISSUE TITLE
Supply callbacks with actual Error instances

### ISSUE THREAD

**Issue by dchekanov** [mailin-api/sendinblue-nodejs-api-npm#12]
Currently this module returns errors like this:

```javascript
if (something !== right) callback('Error description');
```

It would be nice to receive actual Errors instead of Strings:

```javascript
if (something !== right) callback(new Error('Error description'));
```

This would allow error handlers to process all errors in the same way (rely on err.stack and err.message, for example).

**Comment by ekta-slit** [comment]
Hi @dchekanov 

In our latest API V3.0 we have implemented handling of errors and exceptions using Promises.
Suggest you to use https://www.npmjs.com/package/sib-api-v3-sdk to access many other new APIs as well.

Thanks
SendinBlue Team
