### ISSUE TITLE
(valid \'to\' email address required') error even i entered correct email

### ISSUE THREAD

**Issue by abdelrahmanbadr** [mailin-api/sendinblue-nodejs-api-npm#13]
let email = "to@example.net";
	var input =	{ 'to': { email: 'to whom!' },
	'from': ['from@email.com', 'from email!'],
	'subject': 'Test mail form sendinblue',
	'html': 'This is the <h1>HTML</h1>'
};
sendinObj.send_email(input, function(err, response){
    if(err){
        console.log(err);
    } else {
        console.log(response);
    }
});
if i put email in a variable give me this error 
{ code: 'failure',
  message: 'valid \'to\' email address required',
  data: [] }

**Comment by ekta-slit** [comment]
Hi @abdelrahmanbadr 

Your sample `{ 'to': { email: 'to whom!' }` seems incorrect, please refer below:

```
require("../mailin.js");
	var client = new Mailin("https://api.sendinblue.com/v2.0","your access key");
	data = { "to" : {"to@example.net":"to whom!"},
		"from" : ["from@email.com", "from email!"],
		"subject" : "My subject",
		"html" : "This is the HTML",
		"attachment" : ["https://domain.com/path-to-file/filename1.pdf", "https://domain.com/path-to-file/filename2.jpg"]
	}
 
	client.send_email(data).on('complete', function(data) {
		console.log(data);
	});
```
Doc reference: https://apidocs.sendinblue.com/tutorial-sending-transactional-email/

Thanks

**Comment by abdelrahmanbadr** [comment]
no i just didn't put the whole sample.

the is the whole code sample :

var sendinblue = require('sendinblue-api');
var env = require('./environments/env');

	var parameters = { "apiKey": env.sendInBlueKey, "timeout": 5000 };	//Optional parameter: Timeout in MS
	var sendinObj = new sendinblue(parameters);

	let email = "to@example.net";
	var input =	{ 'to': { email: 'to whom!' },
	'from': ['from@email.com', 'from email!'],
	'subject': 'Test mail form sendinblue',
	'html': 'This is the <h1>HTML</h1>'
};

sendinObj.send_email(input, function(err, response){
    if(err){
        console.log(err);
    } else {
        console.log(response);
    }
});

**Comment by abdelrahmanbadr** [comment]
but it will work if don't put email in a variable like that : 
do u have any idea why ?
var input =	{ 'to': { "to@example.net": 'to whom!' },
'from': ['from@email.com', 'from email!'],
'subject': 'Test mail form sendinblue',
'html': 'This is the <h1>HTML</h1>'

**Comment by ekta-slit** [comment]
@abdelrahmanbadr If you use
```
let email = "to@example.net";
var input = { 'to': { email: 'to whom!' }},
```

 Node will not replace `email` value instead its treated as an object key.

**Comment by abdelrahmanbadr** [comment]
Thanks for your help

**Comment by hitenkaram** [comment]
Hi ekta-slit,
Can you guide us in how to achieve this requirement, because this is a valid scenario where you have to call the Sendinblue function to send an email and pass the receiver email id as a parameter from some other function?
I'm also stuck in the same issue. In our case, the above code is a lambda function so we need to pass receiver's email as a parameter to this lambda, please suggest if you have any idea to avoid this issue.
Thanking you in advance.

**Comment by ekta-slit** [comment]
Hi @hitenkaram 

You can do it like this: first initialize the object and use brackets `[]` to set key value.

A simple example:
```
let obj = {};
let key = "to@example.net";
obj[key] = "to whom!";

let field = "to";
let input = {};
input[field] = obj;

console.log(input);
```
Response: 
```
{ to: { 'to@example.net': 'to whom!' } }
```

Thanks

**Comment by hitenkaram** [comment]
Thank you ekta-slit for the help.
