### ISSUE TITLE
{ code: 'failure', message: 'Key Not Found In Database', data: [] }

### ISSUE THREAD

**Issue by Abhijeetjaiswalit** [mailin-api/sendinblue-nodejs-api-npm#15]
Hi @ekta-slit can you please check what is goin wrong. i'm getting this issue.

{ code: 'failure', message: 'Key Not Found In Database', data: [] }

`
const parameters = {
    "apiKey": "key",
    "timeout": 30000,
};
const mailer = new Mailer(parameters);
function sendMail(contactData) {
    
    const emailOptions =
    {
        "from": email,
        "to": email,
        "attr": {
            name: contactData.name,
            email: contactData.email,
            message: contactData.message,
            interestedIn: contactData.interestedIn,
            subject: "subject"
        },
        "id": 21,
    };
    console.log('mailer console',mailer);
    return mailer.send_transactional_template(emailOptions, function (err, response) {
        if (err) {
            console.error(err); // in case of timeout, we never get here...
        }
        console.log(response); // ...nor here...!
    });
}
`

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-nodejs-library
