### ISSUE TITLE
Please provide a correct documentation

### ISSUE THREAD

**Issue by azachar** [mailin-api/sendinblue-nodejs-api-npm#3]
Hello, 
I have been struggling with your outdated documentation. This plugin refers to the official documentation, but when you open the official doc link https://apidocs.sendinblue.com/tutorial-sending-transactional-email/, you will find this example, **that apparently doesn't work.**

```
var client = new Mailin("https://api.sendinblue.com/v2.0","your access key");
    data = { "to" : {"to@example.net":"to whom!"},
        "from" : ["from@email.com", "from email!"],
        "subject" : "My subject",
        "html" : "This is the <h1>HTML</h1>",
        "attachment" : ["https://domain.com/path-to-file/filename1.pdf", "https://domain.com/path-to-file/filename2.jpg"]
    }

    client.send_email(data).on('complete', function(data) {
        console.log(data);
    }); 
```

Your api changed over the time, but there is no updated documentation. 

Also on this plugin page shows an api usage that is super marginal - get_account !?

Instead you should demonstrate the most typical use cases, which are transactional emails & sms. Why you are so relactent to the documentation when you are providing a public API!!

I am really not happy with the current state. Please provide a fix ASAP.

Best regards,
Andrej Zachar

**Comment by pierrre** [comment]
Hello,

> I have been struggling with your outdated documentation. This plugin refers to the official documentation, but when you open the official doc link https://apidocs.sendinblue.com/tutorial-sending-transactional-email/, you will find this example, that apparently doesn't work.

What do you mean by "it doesn't work" ?
I tested the example right now and it works fine.
Do you get an error message?

> Instead you should demonstrate the most typical use cases, which are transactional emails & sms. Why you are so relactent to the documentation when you are providing a public API!!

Example for transactionnal email is available here: https://apidocs.sendinblue.com/tutorial-sending-transactional-email/ (it's the same page you linked)
Example for transactional SMS is available here: https://apidocs.sendinblue.com/mailin-sms/#1

> Also on this plugin page shows an api usage that is super marginal - get_account !?

https://apidocs.sendinblue.com/account/#1
Yes, all API methods are documented.

**Comment by pierrre** [comment]
OK, I misunderstood your question.
The current documentation is for this repository: https://github.com/mailin-api/mailin-api-node-js

I'll keep you informed.

**Comment by ekta-slit** [comment]
Hello,

Please refer this link for transactional Email sample: [https://github.com/mailin-api/sendinblue-nodejs-api-npm/blob/master/examples/send_email.js](https://github.com/mailin-api/sendinblue-nodejs-api-npm/blob/master/examples/send_email.js)
And for transactional SMS refer below sample:

```
var sendinblue = require('sendinblue-api');

var parameters = { "apiKey": "your_api_key", "timeout": 5000 };
var sendinObj = new sendinblue(parameters);

var input = {  "to" : "+331234567890",
        "from" : "From",
        "text" : "Good morning - test",
        "web_url" : "http://example.com",
        "tag" : "Tag1",
        "type" : "transactional"
};

sendinObj.send_sms(input, function(err, response){
    console.log(response);
});
```

Regards
SendinBlue Team

**Comment by jakobrosenberg** [comment]
You should consider updating the official documentation on your website or at least link to proper documentation in the github repository. I'm following links, running in circles between Google, npmjs.com, github.com and apidocs.sendinblue.com looking a link that isn't misleading. It shouldn't be this hard to fix a link or leave a note.

I was about to give up on your API when I finally found the answer here in a closed issue.

**Comment by ekta-slit** [comment]
Hello @jakobrosenberg 

Our upcoming release of API Version 3 documentation is the one you will definitely going to like.
Thank you for your feedback & kind patience with us.

Regards
SendinBlue Team
