### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by jawadst** [mailin-api/sendinblue-nodejs-api-npm#7]
Do you have plans to implement a promise-based interface as an addition to the current callback-based interface?

We are using the SendinBlue API client with Koa generators and promises make it our life easier. Currently, we have to wrap all the calls into our own promises so it would be great to have that out of the box.

**Comment by Parvindersib** [comment]
Hello @jawadst,

Thank you for contacting us.
For now we do not have any plan to implement promise-based interface as an addition to the current callback-based interface in v2. If you want to implement them we will be very happy and appreciate it.

Regards
SendinBlue Team
