### ISSUE TITLE
Request Failed

### ISSUE THREAD

**Issue by jawadst** [mailin-api/sendinblue-nodejs-api-npm#9]
The error message that the library is sending when a request fail is pretty useless as it is: "Request Failed" (https://github.com/mailin-api/sendinblue-nodejs-api-npm/blob/master/sendinblue-api.js#L30)

Can you update the library to pass the original error back to the callback so that it's easier to debug what failed?

For instance, I am using nock to mock the HTTP calls and when nock throws and error, that error is caught by the library and I cannot see what went wrong.

**Comment by ekta-slit** [comment]
Hello @jawadst 

Thank you for contacting us.
[This](https://github.com/mailin-api/sendinblue-nodejs-api-npm/blob/master/sendinblue-api.js#L30) is our generalised way of error handling.
For original error you can simply edit the line as mentioned below at your end.
`cb("Request Failed", null);` to `cb(response, null);`

Regards
SendinBlue Team
